version: '3.8'
services:
  postgres-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=coffeeshop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - coffee-shop-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  customer-service:
    build:
      context: .
      dockerfile: ./customer-service/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
      authentication-service:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/coffeeshop_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=customer_schema
    networks:
      - coffee-shop-network

  notification-service:
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      postgres-db:
        condition: service_healthy
      authentication-service:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/coffeeshop_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=notification_schema
    networks:
      - coffee-shop-network

  order-service:
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      postgres-db:
        condition: service_healthy
      authentication-service:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/coffeeshop_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=order_schema
    networks:
      - coffee-shop-network

  queue-service:
    build:
      context: .
      dockerfile: ./queue-service/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      postgres-db:
        condition: service_healthy
      authentication-service:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/coffeeshop_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=queue_schema
    networks:
      - coffee-shop-network

  shop-service:
    build:
      context: .
      dockerfile: ./shop-service/Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      postgres-db:
        condition: service_healthy
      authentication-service:
       condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/coffeeshop_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=shop_schema
    networks:
      - coffee-shop-network

  authentication-service:
    build:
      context: .
      dockerfile: ./authentication-service/Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/coffeeshop_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=auth_schema
    networks:
      - coffee-shop-network

networks:
  coffee-shop-network:
    driver: bridge

volumes:
  postgres-data: