spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/coffeeshop_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: customer_schema
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8080
auth-service:
  url: ${AUTH_SERVICE_URL:http://auth-service:8085/api/v1/auth/validate}
logging:
  level:
    org.springframework.web: DEBUG
    com.coffeeshop: DEBUG