spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/coffeeshop_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8085
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
jwt:
  secret: ${JWT_SECRET:2996a4a3ff6d7c1c5e296829e349fee5f4c4b61ada517260e0f4cf3a227f6e08} # Use a 32+ character random string
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000} # Adjust for your frontend